# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'RNApp' do
	# Uncomment the next line if you're using Swift or would like to use dynamic frameworks
	# use_frameworks!

	# Pods for RNApp
	pod 'React', :path => '../node_modules/react-native'
	pod 'React/RCTGeolocation', :path => '../node_modules/react-native'
	pod 'React/RCTImage', :path => '../node_modules/react-native'
	pod 'React/RCTNetwork', :path => '../node_modules/react-native'
	pod 'React/RCTText', :path => '../node_modules/react-native'
	pod 'React/RCTWebSocket', :path => '../node_modules/react-native'

	pod 'RCTMapboxGL', :path => '../node_modules/react-native-mapbox-gl/ios'

	target 'RNAppTests' do
		inherit! :search_paths
		# Pods for testing
	end

end
